import { useEffect, useMemo, useState } from 'react'
import { ChevronLeft, ChevronRight, Maximize, Pause, Play, RotateCcw, SlidersHorizontal, X, Zap } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { capoShapeKey, chromatic, simplifyChord, transposeLine, type Notation } from './music'
import type { Settings, Song, Setlist } from './data'

type UpdateSong = (song: Song) => void

const keyNames = [...chromatic]
const keyIndex = (key: string) => Math.max(0, keyNames.indexOf(key.replace('b', '#')))
const shiftedKey = (key: string, amount: number) => keyNames[(keyIndex(key) + amount + 24) % 12]
const displayDate = (value: string) => value === 'This Sunday' ? value : value

export function DashboardV2({ songs, setlists, onCreateSong, onCreateSetlist }: { songs: Song[]; setlists: Setlist[]; onCreateSong: () => void; onCreateSetlist: () => void }) {
  const favorites = songs.filter((song) => song.favorite).slice(0, 3)
  const recent = songs.filter((song) => song.lastPlayed).concat(songs).filter((song, index, items) => items.findIndex((item) => item.id === song.id) === index).slice(0, 3)
  const nextSet = setlists[0]
  return <div className="page dashboard-v2"><div className="dashboard-title"><div><div className="eyebrow">Worship Guitar</div><h1>Your worship songs,<br /><em>always ready.</em></h1></div><div className="dashboard-mark">WG</div></div><div className="quick-actions"><button onClick={onCreateSong}><span>＋</span><b>Add song</b><small>Build your library</small></button><button onClick={onCreateSetlist}><span>☷</span><b>Create setlist</b><small>Plan Sunday</small></button><Link to="/chords"><span>♬</span><b>Chord library</b><small>Find a shape</small></Link><Link to={`/live/${nextSet?.songIds[0] || songs[0]?.id}`}><span>▶</span><b>Start live mode</b><small>Play now</small></Link></div><div className="dashboard-columns"><section><div className="section-heading"><div><span className="eyebrow">Pick up where you left off</span><h2>Recent songs</h2></div><Link to="/songs">All songs <ChevronRight size={14} /></Link></div><div className="song-list">{recent.map((song) => <SongRowCompact key={song.id} song={song} />)}</div>{favorites.length > 0 && <><div className="section-heading dashboard-subheading"><div><span className="eyebrow">Your go-to songs</span><h2>Favorites</h2></div></div><div className="song-list">{favorites.map((song) => <SongRowCompact key={song.id} song={song} />)}</div></>}</section><section className="sunday-card"><span className="eyebrow">Up next</span><h2>{nextSet?.name || 'Build your Sunday set'}</h2><p>{nextSet?.date || 'A setlist makes every service easier to start.'}</p>{nextSet && <><div className="sunday-count"><strong>{nextSet.songIds.length}</strong><span>songs<br />ready to play</span></div><div className="setlist-mini">{nextSet.songIds.slice(0, 4).map((songId, index) => <div key={songId}><span>{String(index + 1).padStart(2, '0')}</span>{songs.find((song) => song.id === songId)?.title || 'Untitled song'}</div>)}</div><Link className="primary-button" to={`/live/${nextSet.songIds[0]}`}>Start worship <ChevronRight size={15} /></Link></>}</section></div></div>
}

function SongRowCompact({ song }: { song: Song }) { return <Link className="song-row" to={`/songs/${song.id}`}><span className="song-art">{song.title.slice(0, 1)}</span><span className="song-meta"><strong>{song.title}</strong><small>{song.artist}</small></span><span className="key-pill">{song.currentKey}</span><ChevronRight size={17} /></Link> }

export function SongsPageV2({ songs, onCreate, onUpdate, onDelete }: { songs: Song[]; onCreate: () => void; onUpdate: UpdateSong; onDelete: (song: Song) => void }) {
  const [query, setQuery] = useState('')
  const [favoritesOnly, setFavoritesOnly] = useState(false)
  const [key, setKey] = useState('all')
  const [sort, setSort] = useState('recent')
  const filtered = useMemo(() => songs.filter((song) => {
    const matchesText = `${song.title} ${song.artist} ${song.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())
    return matchesText && (!favoritesOnly || song.favorite) && (key === 'all' || song.currentKey === key)
  }).sort((a, b) => sort === 'title' ? a.title.localeCompare(b.title) : (b.lastPlayed || '').localeCompare(a.lastPlayed || '')), [songs, query, favoritesOnly, key, sort])
  return <div className="page"><div className="v2-library-header"><div><div className="eyebrow">Your personal songbook</div><h1>Songs</h1><p className="page-intro">{songs.length} songs ready for Sunday.</p></div><button className="primary-button" onClick={onCreate}><span>＋</span>Add song</button></div>
    <div className="library-filters"><input className="wide-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search title, artist, or tag" /><button className={favoritesOnly ? 'filter-button selected' : 'filter-button'} onClick={() => setFavoritesOnly(!favoritesOnly)}>★ Favorites</button><select value={key} onChange={(event) => setKey(event.target.value)}><option value="all">All keys</option>{keyNames.map((item) => <option key={item}>{item}</option>)}</select><select value={sort} onChange={(event) => setSort(event.target.value)}><option value="recent">Recently played</option><option value="title">Title A–Z</option></select></div>
    <div className="v2-song-grid">{filtered.map((song) => <article className="v2-song-card" key={song.id}><Link to={`/songs/${song.id}`}><span className="song-art large-art">{song.title.slice(0, 1)}</span><div className="v2-song-copy"><h2>{song.title}</h2><p>{song.artist}</p><div className="song-facts"><span>Key <b>{song.currentKey}</b></span><span>Capo <b>{song.capo}</b></span><span>{song.bpm} BPM</span></div></div></Link><div className="v2-song-actions"><button aria-label={song.favorite ? 'Remove favorite' : 'Add favorite'} className={song.favorite ? 'star active' : 'star'} onClick={() => onUpdate({ ...song, favorite: !song.favorite })}>★</button><Link className="text-button" to={`/songs/${song.id}`}>Open <ChevronRight size={14} /></Link><button aria-label="Delete song" className="icon-button subtle" onClick={() => window.confirm(`Delete ${song.title}?`) && onDelete(song)}><X size={15} /></button></div></article>)}{!filtered.length && <div className="empty"><h2>No songs match</h2><p>Try another filter or add your first song.</p></div>}</div>
  </div>
}

export function SongPageV2({ songs, settings, onUpdate, onSettings }: { songs: Song[]; settings: Settings; onUpdate: UpdateSong; onSettings: (settings: Settings) => void }) {
  const { songId } = useParams(); const navigate = useNavigate(); const song = songs.find((item) => item.id === songId)
  if (!song) return <div className="empty"><h2>Song not found</h2><Link className="secondary-button" to="/songs">Back to songs</Link></div>
  const interval = (keyIndex(song.currentKey) - keyIndex(song.key) + 12) % 12
  const changeKey = (amount: number) => onUpdate({ ...song, currentKey: shiftedKey(song.currentKey, amount), lastPlayed: new Date().toISOString() })
  const setCapo = (capo: number) => onUpdate({ ...song, capo: Math.max(0, Math.min(12, capo)) })
  const shapeKey = capoShapeKey(song.currentKey, song.capo, settings.notation)
  return <div className="page song-page"><button className="back-button" onClick={() => navigate('/songs')}><ChevronLeft size={16} />All songs</button><div className="v2-song-heading"><div><div className="eyebrow">{song.artist}</div><h1>{song.title}</h1><div className="song-tags"><span>Original key {song.key}</span><span>{song.bpm} BPM</span></div></div><Link className="primary-button" to={`/live/${song.id}`}><Zap size={17} />Live mode</Link></div>
    <section className="key-deck"><div className="deck-key"><span className="eyebrow">Sounding key</span><strong>{song.currentKey}</strong><small>Original: {song.key}</small></div><div className="quick-transpose"><span className="eyebrow">Quick transpose</span><div><button onClick={() => changeKey(-2)}>-2</button><button onClick={() => changeKey(-1)}>-1</button><button className="current-key" onClick={() => onUpdate({ ...song, currentKey: song.key })}>{song.currentKey}</button><button onClick={() => changeKey(1)}>+1</button><button onClick={() => changeKey(2)}>+2</button><button title="Reset to original" onClick={() => onUpdate({ ...song, currentKey: song.key })}><RotateCcw size={14} /></button></div></div><label className="key-select"><span className="eyebrow">Choose key</span><select value={song.currentKey} onChange={(event) => onUpdate({ ...song, currentKey: event.target.value })}>{keyNames.map((item) => <option key={item}>{item}</option>)}</select></label><div className="capo-deck"><span className="eyebrow">Capo</span><div><button onClick={() => setCapo(song.capo - 1)}>−</button><strong>{song.capo}</strong><button onClick={() => setCapo(song.capo + 1)}>＋</button></div><small>Playing shapes: <b>{shapeKey}</b></small></div></section>
    <div className="song-layout"><article className="lyrics-panel"><div className="display-label">Showing transposed chords · {settings.simplify ? 'Simplified' : 'Original'} mode</div>{song.sections.map((section) => <section className="song-section" key={section.id}><h3>{section.name}</h3>{section.lines.map((line, index) => <div className={index === 0 || /^[A-G]/.test(line) ? 'chord-line' : 'lyric-line'} key={`${section.id}-${index}`}>{settings.simplify ? simplifyChord(transposeLine(line, interval, settings.notation)) : transposeLine(line, interval, settings.notation)}</div>)}{section.note && <div className="performance-note">{section.note}</div>}</section>)}</article><aside className="song-side-stack"><section className="guitar-setup"><div className="section-heading"><div><span className="eyebrow">Guitar setup</span><h2>Two players, one sound.</h2></div><SlidersHorizontal size={18} /></div><GuitarCard name="Guitar 1" soundingKey={song.currentKey} capo={song.capo} shapeKey={shapeKey} /><GuitarCard name="Guitar 2" soundingKey={song.currentKey} capo={5} shapeKey={capoShapeKey(song.currentKey, 5, settings.notation)} /><span className="same-key">✓ Same sounding key</span></section><section className="notes-panel v2-notes"><div className="eyebrow">Performance notes</div><textarea value={song.notes} onChange={(event) => onUpdate({ ...song, notes: event.target.value })} placeholder="Start softly, build at the bridge..." /><label className="toggle-line"><input type="checkbox" checked={settings.simplify} onChange={(event) => onSettings({ ...settings, simplify: event.target.checked })} /> Simplify chords</label></section></aside></div>
  </div>
}

function GuitarCard({ name, soundingKey, capo, shapeKey }: { name: string; soundingKey: string; capo: number; shapeKey: string }) { return <div className="guitar-card"><div><strong>{name}</strong><small>Sounding key</small></div><b>{soundingKey}</b><div><small>Capo {capo}</small><small>Shapes {shapeKey}</small></div></div> }

export function SetlistsPageV2({ songs, setlists, onCreate, onUpdate, onDelete }: { songs: Song[]; setlists: Setlist[]; onCreate: () => void; onUpdate: (setlist: Setlist) => void; onDelete: (setlist: Setlist) => void }) { return <div className="page"><div className="v2-library-header"><div><div className="eyebrow">Plan the service</div><h1>Setlists</h1><p className="page-intro">Open the set, then start playing.</p></div><button className="primary-button" onClick={onCreate}>＋ New setlist</button></div><div className="setlist-grid">{setlists.map((setlist) => <article className="setlist-card v2-setlist" key={setlist.id}><div className="setlist-card-top"><span className="date-stamp">{displayDate(setlist.date)}</span><button aria-label="Delete setlist" className="icon-button subtle" onClick={() => window.confirm(`Delete ${setlist.name}?`) && onDelete(setlist)}><X size={15} /></button></div><h2>{setlist.name}</h2><p>{setlist.songIds.length} songs</p><div className="setlist-songs">{setlist.songIds.map((songId, index) => <div key={`${setlist.id}-${songId}`}><span>{String(index + 1).padStart(2, '0')}</span>{songs.find((song) => song.id === songId)?.title || 'Missing song'}</div>)}</div><div className="setlist-footer"><Link className="primary-button small" to={`/live/${setlist.songIds[0] || songs[0]?.id}`}><Play size={15} />Start worship</Link><select aria-label="Add a song" onChange={(event) => event.target.value && onUpdate({ ...setlist, songIds: [...setlist.songIds, event.target.value] })} value=""><option value="">Add song...</option>{songs.filter((song) => !setlist.songIds.includes(song.id)).map((song) => <option value={song.id} key={song.id}>{song.title}</option>)}</select></div></article>)}</div></div> }

export function LivePageV2({ songs, settings, onSettings }: { songs: Song[]; settings: Settings; onSettings: (settings: Settings) => void }) {
  const { songId } = useParams(); const navigate = useNavigate(); const songIndex = songs.findIndex((song) => song.id === songId); const song = songs[songIndex]; const [section, setSection] = useState(0); const [playing, setPlaying] = useState(false); const [fontSize, setFontSize] = useState(settings.fontSize || 1); const [speed, setSpeed] = useState(settings.autoScrollSpeed || 1); const [showControls, setShowControls] = useState(true)
  useEffect(() => { if (!playing) return; const timer = window.setInterval(() => window.scrollBy({ top: speed, behavior: 'smooth' }), 100); return () => window.clearInterval(timer) }, [playing, speed])
  useEffect(() => { const handler = (event: KeyboardEvent) => { if (event.target instanceof HTMLInputElement || event.target instanceof HTMLTextAreaElement || event.target instanceof HTMLSelectElement) return; if (event.key === 'ArrowRight') setSection((current) => Math.min(current + 1, (song?.sections.length || 1) - 1)); if (event.key === 'ArrowLeft') setSection((current) => Math.max(current - 1, 0)); if (event.code === 'Space') { event.preventDefault(); setPlaying((current) => !current) } if (event.key.toLowerCase() === 'f') document.documentElement.requestFullscreen?.(); if (event.key === 'Escape') navigate(`/songs/${songId}`) }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler) }, [navigate, song?.sections.length, songId])
  if (!song) return <div className="empty"><h2>Nothing to play</h2><Link className="secondary-button" to="/songs">Browse songs</Link></div>
  const current = song.sections[section]; const previousSong = songs[songIndex - 1]; const nextSong = songs[songIndex + 1]; const setFont = (value: number) => { const next = Math.max(.8, Math.min(1.5, value)); setFontSize(next); onSettings({ ...settings, fontSize: next }) }; const setScrollSpeed = (value: number) => { setSpeed(value); onSettings({ ...settings, autoScrollSpeed: value }) }
  return <div className="live-page live-v2"><header className="live-header"><Link to={`/songs/${song.id}`} className="brand"><span className="brand-mark"><Zap size={17} /></span><span>Worship <b>Guitar</b></span></Link><div className="live-status"><span className="live-dot" />Live · {song.currentKey} · Capo {song.capo}</div><button aria-label="Exit live mode" className="icon-button" onClick={() => navigate(`/songs/${song.id}`)}><X size={20} /></button></header><main className="live-content"><div className="live-song-heading"><div className="eyebrow">{song.artist}</div><h1>{song.title}</h1><div className="live-meta"><span>Sounding key <b>{song.currentKey}</b></span><span>Playing shapes <b>{capoShapeKey(song.currentKey, song.capo, settings.notation)}</b></span><span>Capo <b>{song.capo}</b></span></div></div><div className="section-tabs">{song.sections.map((item, index) => <button className={index === section ? 'active' : ''} onClick={() => setSection(index)} key={item.id}>{item.name}</button>)}</div><article className="live-lyrics" style={{ fontSize: `${fontSize}em` }}>{current.lines.map((line, index) => <div className={index === 0 || /^[A-G]/.test(line) ? 'live-chord-line' : 'live-lyric-line'} key={`${current.id}-${index}`}>{line}</div>)}{current.note && <div className="live-note">{current.note}</div>}</article></main><button className="control-toggle" onClick={() => setShowControls(!showControls)}>{showControls ? 'Hide controls' : 'Show controls'}</button>{showControls && <footer className="live-controls live-v2-controls"><button aria-label="Previous song" className="icon-button" disabled={!previousSong} onClick={() => previousSong && navigate(`/live/${previousSong.id}`)}><ChevronLeft size={22} /></button><button aria-label="Previous section" className="icon-button" onClick={() => setSection(Math.max(0, section - 1))}><ChevronLeft size={17} /></button><button className="play-button" onClick={() => setPlaying(!playing)}>{playing ? <Pause size={17} /> : <Play size={17} />}{playing ? 'Pause' : 'Auto-scroll'}</button><button aria-label="Next section" className="icon-button" onClick={() => setSection(Math.min(song.sections.length - 1, section + 1))}><ChevronRight size={17} /></button><button aria-label="Next song" className="icon-button" disabled={!nextSong} onClick={() => nextSong && navigate(`/live/${nextSong.id}`)}><ChevronRight size={22} /></button><div className="live-tools"><button onClick={() => setFont(fontSize - .1)}>A−</button><button onClick={() => setFont(1)}>A</button><button onClick={() => setFont(fontSize + .1)}>A＋</button><button onClick={() => setScrollSpeed(speed === 1 ? 2 : speed === 2 ? 3 : 1)}>Speed {speed === 1 ? 'slow' : speed === 2 ? 'normal' : 'fast'}</button><button aria-label="Fullscreen" onClick={() => document.documentElement.requestFullscreen?.()}><Maximize size={14} /></button></div></footer>}</div>
}
